### ISSUE TITLE
Can it work for *.vue files?

### ISSUE THREAD

**Issue by pciapcib** [brenopolanski/css-flexbox-sublime-snippets#1]
Hello, I'm a web developer who is using Vue.js.
I hope this awesome plugin can work for *.vue files.
Is it possible? Thanks!

**Comment by brenopolanski** [comment]
Hi @pciapcib 

Is possible. You can contribute and add this feature for me?

is very simple, you will edit each file `.sublime-snippet` and put `source.vue` in tag `<scope>`.

### Example:

```
<snippet>
	<content><![CDATA[
align-content: ${1:flex-start|flex-end|center|space-between|space-around|stretch};
]]></content>
	<tabTrigger>flexcont</tabTrigger>
	<scope>source.css, source.scss, source.sass, source.less, source.styl, source.vue</scope>
	<description>Flexbox - align-content: flex-start;</description>
</snippet>
```

Make sense for you?

**Comment by brenopolanski** [comment]
Hey @pciapcib now `css-flexbox-sublime-snippets` supports *.vue files :)

See: https://github.com/brenopolanski/css-flexbox-sublime-snippets/pull/3
